include:
- remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
- image
- test

build-image:
  stage: image
  extends: .container-builder-cscs-zen2
  variables:
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/public/aiida-icon:latest
    DOCKERFILE: ci/Dockerfile
    CSCS_REBUILD_POLICY: if-not-exists # always

run-tests:
  stage: test
  needs: [build-image]
  extends: .container-runner-lightweight-zen2
  image: $CSCS_REGISTRY_PATH/public/aiida-icon:latest
  variables:
    FIRECREST_URL: https://api.cscs.ch/cw/firecrest/v2
  script:
  - hatch run cscs-ci:verdi presto -p cscsci
  - hatch run cscs-ci:verdi plugin list aiida.transports
  - hatch run cscs-ci:verdi computer setup -n --config ci/santis_setup.yaml
  - hatch run cscs-ci:verdi computer configure firecrest santis -n --config ci/santis_config.yaml --url=$FIRECREST_URL --client-secret=$FIRECREST_SECRET --billing-account=csstaff
  - hatch run cscs-ci:verdi computer test santis
  - hatch run cscs-ci:test
