name: static-analysis

on:
  push:
    branches: [main]
  pull_request:
    # always

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml

    - name: install Python dependencies
      run: |
        uv pip install --system pre-commit hatch


    - name: pre-commit
      run: pre-commit run --all-files
