on:
  release:
    types:
    - published

name: release

permissions: {}

jobs:
  build:
    name: "Build distribution artifacts"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install build system
      run: |
        pip install --upgrade pip
        pip install hatch

    - name: Build sdist and wheel
      run: hatch build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aiida-icon-dist
        path: ./dist/**

  publish:
    name: upload release to pypi
    runs-on: ubuntu-latest
    needs: build
    environment: release
    permissions:
      id-token: write
    steps:
    - name: retrieve distribution artifacts
      uses: actions/download-artifact@v4
      with:
        name: aiida-icon-dist
        path: dist

    - name: Publish package to pypi
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
