on:
  release:
    types:
    - published

name: release

jobs:
  build:
    name: "Build distribution artifacts"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install build system
      run: |
        pip install --upgrade pip
        pip install hatch

    - name: Build sdist and wheel
      run: hatch build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: aiida-icon-dist
        path: ./dist/**

  publish:
    name: upload release to pypi
    runs-on: ubuntu-latest
    needs: build
    environment: release
    permissions:
      id-token: write
    steps:
    - name: retrieve distribution artifacts
      uses: actions/download-artifact@v3
      with:
        name: aiida-icon-dist
        path: dist

    - name: Publish package to pypi
      uses: pypa/gh-action-pypi-publish@release/v1
